### ISSUE TITLE
I can't make it work...

### ISSUE THREAD

**Issue by CoVoCre** [of-human-bondage/react-proptypes-intellisense#58]
I guess I'm not competent enough to understand my mistake, but based on the readme I cannot get any further.
I have the project in a folder : 
<img width="364" alt="capture d ecran 2018-07-19 a 16 48 30" src="https://user-images.githubusercontent.com/25605953/42950136-a63c0fca-8b73-11e8-89a5-8e5c43b93b76.png">

with the jsconfig.json at the root of that folder : 
<img width="299" alt="capture d ecran 2018-07-19 a 16 48 40" src="https://user-images.githubusercontent.com/25605953/42950179-bcec1512-8b73-11e8-9a3e-f075f93fae25.png">

And then I have a component with lots of proptypes : 
<img width="1377" alt="capture d ecran 2018-07-19 a 16 51 40" src="https://user-images.githubusercontent.com/25605953/42950325-0a30ef96-8b74-11e8-9011-f7f2ed4b7a9e.png">

And I import this last one into another : 
<img width="1439" alt="capture d ecran 2018-07-19 a 16 52 18" src="https://user-images.githubusercontent.com/25605953/42950358-1f08ea90-8b74-11e8-828a-8cdebfe11ff9.png">

But then when I try to use it like the example, it doesn't suggest anything. I dont know what to do : 
<img width="1440" alt="capture d ecran 2018-07-19 a 16 54 05" src="https://user-images.githubusercontent.com/25605953/42950487-6bb7573c-8b74-11e8-87f3-a1bcd2d03d66.png">
<img width="1440" alt="capture d ecran 2018-07-19 a 16 54 17" src="https://user-images.githubusercontent.com/25605953/42950499-71ba8096-8b74-11e8-9a91-f74265c04ec5.png">

**Comment by kv4sha** [comment]
Hi! 
Try to start typing props or press Ctrl + Space(windows) / Control + Space(macOS)

**Comment by CoVoCre** [comment]
@kv4sha  Thanks for your help. I've got it now !!!

Wo I've found out some things that might be useful for others : I've found the useful blue suggestions for the first prop I started typing or use space+ ctrl : 
<img width="999" alt="capture d ecran 2018-07-19 a 17 24 30" src="https://user-images.githubusercontent.com/25605953/42952475-d59f3f1c-8b78-11e8-8098-253716ad11cd.png">

But then for the next ones it doesn't do that anymore wether I start typing or press space+ctrl : 
<img width="1065" alt="capture d ecran 2018-07-19 a 17 25 03" src="https://user-images.githubusercontent.com/25605953/42952543-fc9de028-8b78-11e8-9eb7-b58819361518.png">
<img width="918" alt="capture d ecran 2018-07-19 a 17 25 21" src="https://user-images.githubusercontent.com/25605953/42952544-fcc04294-8b78-11e8-8948-825931d9d412.png">

And actually, I just had to enter something in the other props for the next suggestions to appear : 
<img width="842" alt="capture d ecran 2018-07-19 a 17 30 48" src="https://user-images.githubusercontent.com/25605953/42952817-819b9e82-8b79-11e8-9520-4bd671408dca.png">

Thanks a lot ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️

**Comment by kv4sha** [comment]
We use babel
We have this problem cuz prop={} is incorrect js for babel

**Comment by CoVoCre** [comment]
And would it be impossible to, without pressing ctrl+space/cmd+space on windows, autosuggest props ? It would save time for each prop !

**Comment by kv4sha** [comment]
We can't do this cuz we use native vscode behavior for this (CompletionItemProvider)
